/* Generated By:JJTree: Do not edit this line. Accept.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class Accept extends SimpleNode {
  public Accept(int id) {
    super(id);
  }

  public Accept(AutoAnalyserParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=092406c825d9494b4ca9040bf5245eb7 (do not edit this line) */
