/* Generated By:JJTree: Do not edit this line. accept.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class accept extends SimpleNode {
  public accept(int id) {
    super(id);
  }

  public accept(AutoAnalyserParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0c486ebe8a771dd6f8bb61ddb277b2e0 (do not edit this line) */
