/* Generated By:JavaCC: Do not edit this line. AutoAnalyserParserTreeConstants.java Version 5.0 */
public interface AutoAnalyserParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTREAD = 1;
  public int JJTOPERATIONS = 2;
  public int JJTACCEPT = 3;
  public int JJTEXPR1 = 4;
  public int JJTCONCATENATION = 5;
  public int JJTINTERSECTION = 6;
  public int JJTUNION = 7;
  public int JJTDIFFERENCE = 8;
  public int JJTEXPR2 = 9;
  public int JJTCOMPLEMENT = 10;
  public int JJTEXPR3 = 11;
  public int JJTSAVES = 12;
  public int JJTIDENTIFIER = 13;
  public int JJTLOADDOTTY = 14;
  public int JJTFILENAME = 15;
  public int JJTINPUT = 16;


  public String[] jjtNodeName = {
    "Start",
    "Read",
    "Operations",
    "Accept",
    "Expr1",
    "Concatenation",
    "Intersection",
    "Union",
    "Difference",
    "Expr2",
    "Complement",
    "Expr3",
    "Saves",
    "Identifier",
    "Loaddotty",
    "Filename",
    "Input",
  };
}
/* JavaCC - OriginalChecksum=ab7f793f15c6572caa00bb3a82a467ae (do not edit this line) */
