/* Generated By:JavaCC: Do not edit this line. AutoAnalyserParserTreeConstants.java Version 5.0 */
public interface AutoAnalyserParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTREAD = 1;
  public int JJTOPERATIONS = 2;
  public int JJTINPUT = 3;
  public int JJTACCEPT = 4;
  public int JJTEXPRESSION = 5;
  public int JJTEXPR1 = 6;
  public int JJTSUM = 7;
  public int JJTCONCATENATION = 8;
  public int JJTINTERSECTION = 9;
  public int JJTUNION = 10;
  public int JJTDIFFERENCE = 11;
  public int JJTEXPR2 = 12;
  public int JJTCOMPLEMENT = 13;
  public int JJTEXPR3 = 14;
  public int JJTSAVES = 15;
  public int JJTIDENTIFIER = 16;
  public int JJTLOADDOTTY = 17;
  public int JJTFILENAME = 18;


  public String[] jjtNodeName = {
    "start",
    "read",
    "operations",
    "input",
    "accept",
    "expression",
    "expr1",
    "sum",
    "concatenation",
    "intersection",
    "union",
    "difference",
    "expr2",
    "complement",
    "expr3",
    "saves",
    "identifier",
    "loaddotty",
    "filename",
  };
}
/* JavaCC - OriginalChecksum=b1bb47e50812546748ca834bf044347a (do not edit this line) */
