/* Generated By:JJTree&JavaCC: Do not edit this line. AutoAnalyserParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AutoAnalyserParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EQUAL = 5;
  /** RegularExpression Id. */
  int VARIABLE = 6;
  /** RegularExpression Id. */
  int ENDLINE = 7;
  /** RegularExpression Id. */
  int STRING = 8;
  /** RegularExpression Id. */
  int COMPLEMENT = 9;
  /** RegularExpression Id. */
  int CONCATENATION = 10;
  /** RegularExpression Id. */
  int INTERSECTION = 11;
  /** RegularExpression Id. */
  int UNION = 12;
  /** RegularExpression Id. */
  int DIFFERENCE = 13;
  /** RegularExpression Id. */
  int ACCEPT = 14;
  /** RegularExpression Id. */
  int READ = 15;
  /** RegularExpression Id. */
  int WRITE = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"=\"",
    "<VARIABLE>",
    "\";\"",
    "<STRING>",
    "\"!\"",
    "\".\"",
    "\"/\\\\\"",
    "\"|\"",
    "\"-\"",
    "\".accept\"",
    "\".read\"",
    "\".write\"",
    "\"(\"",
    "\")\"",
  };

}
