/* Generated By:JJTree: Do not edit this line. complement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class complement extends SimpleNode {
  public complement(int id) {
    super(id);
  }

  public complement(AutoAnalyserParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=10972841e68c7da6e4da39f0a131532e (do not edit this line) */
