/* Generated By:JJTree: Do not edit this line. Complement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class Complement extends SimpleNode {

  
  public Complement(int id) {
    super(id);
  }

  public Complement(AutoAnalyserParser p, int id) {
    super(p, id);
  }

  public void execute() {
    System.out.println("EXECUTE COMPLEMENT");
  }
}
/* JavaCC - OriginalChecksum=9710604948378a16cf4cc7a9a3c1c1d4 (do not edit this line) */
