/* Generated By:JJTree: Do not edit this line. Concatenation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class Concatenation extends SimpleNode {
  public Concatenation(int id) {
    super(id);
  }

  public Concatenation(AutoAnalyserParser p, int id) {
    super(p, id);
  }

  public Automata execute(){
    for(int i=0; i < children.length; i++) {
      if (children[i] instanceof Identifier){
        System.out.println(((Identifier) children[i]).name);
      } else if (children[i] instanceof Expr1){
        children[i].execute();
      } else {
        System.out.println(children[i]);
      }
    }
    return null;
  }

}
/* JavaCC - OriginalChecksum=2f6aeffe93302923e342396ae6d39804 (do not edit this line) */
