/* Generated By:JJTree: Do not edit this line. difference.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class difference extends SimpleNode {
  public difference(int id) {
    super(id);
  }

  public difference(AutoAnalyserParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=efa021e3c894ac48ee15001e611bc19e (do not edit this line) */
