/* Generated By:JJTree: Do not edit this line. expr1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class expr1 extends SimpleNode {
  public expr1(int id) {
    super(id);
  }

  public expr1(AutoAnalyserParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=daee2a791a0e6f2fe2b77b2be24adac4 (do not edit this line) */
