/* Generated By:JJTree: Do not edit this line. expr3.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class expr3 extends SimpleNode {
  public expr3(int id) {
    super(id);
  }

  public expr3(AutoAnalyserParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3fe92af2834efa7de4bc13c37d9d56ce (do not edit this line) */
