/* Generated By:JJTree: Do not edit this line. expr2.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class expr2 extends SimpleNode {
  public expr2(int id) {
    super(id);
  }

  public expr2(AutoAnalyserParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=89897d34731c74f73575a3dcfcb2339c (do not edit this line) */
