/* Generated By:JJTree: Do not edit this line. Expr1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class Expr1 extends SimpleNode {
  public Expr1(int id) {
    super(id);
  }

  public Expr1(AutoAnalyserParser p, int id) {
    super(p, id);
  }

 public void execute() {
    System.out.println("Execute Expr1");


    for(int i=0; i < children.length; i++) {
      children[i].execute();
    }
    
  }
}
/* JavaCC - OriginalChecksum=b245cbe223e1688cfdbdf42df5c0c1ff (do not edit this line) */
