/* Generated By:JJTree: Do not edit this line. Expression2.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class Expression2 extends SimpleNode {
  public Expression2(int id) {
    super(id);
  }

  public Expression2(AutoAnalyserParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=02b952d517f6aaf184f704c9df362f89 (do not edit this line) */
