/* Generated By:JJTree: Do not edit this line. expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class expression extends SimpleNode {
  public expression(int id) {
    super(id);
  }

  public expression(AutoAnalyserParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2a77fcb5a77f6d63b8bd4d5f759d60ac (do not edit this line) */
