/* Generated By:JJTree: Do not edit this line. Expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class Expression extends SimpleNode {
  public Expression(int id) {
    super(id);
  }

  public Expression(AutoAnalyserParser p, int id) {
    super(p, id);
  }

  public Automata execute() {
    Automata res = null;

    for(int i=0; i < children.length; i++) {
      if (children[i] instanceof Expr1){
        res = children[i].execute();
      } else {
        System.out.println("Shouldn't go here1");
      }
    }
    return res;
  }
}
/* JavaCC - OriginalChecksum=0fc795c4d90a18d9dfaa0f5220f7a94b (do not edit this line) */
