/* Generated By:JJTree: Do not edit this line. Expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class Expression extends SimpleNode {
  public Expression(int id) {
    super(id);
  }

  public Expression(AutoAnalyserParser p, int id) {
    super(p, id);
  }

  public void execute() {
    System.out.println("Execute Expression");


    for(int i=0; i < children.length; i++) {
      children[i].execute();
    }
    
  }
}
/* JavaCC - OriginalChecksum=0fc795c4d90a18d9dfaa0f5220f7a94b (do not edit this line) */
