/* Generated By:JJTree: Do not edit this line. Filename.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class Filename extends SimpleNode {

   public String name = null;
   
  public Filename(int id) {
    super(id);
  }

  public Filename(AutoAnalyserParser p, int id) {
    super(p, id);
  }

  public void execute() {
        System.out.println("FILENAME");
    }

    public Object jjtGetValue() { return name; }

    public String toString() { return AutoAnalyserParserTreeConstants.jjtNodeName[id] + " " + name; }
}
/* JavaCC - OriginalChecksum=f11af67a623de0e453e6c472b6ce715a (do not edit this line) */
