/* Generated By:JJTree: Do not edit this line. filename.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class filename extends SimpleNode {
  
    public String name = null;
    public filename(int id) {
    super(id);
    }

    public filename(AutoAnalyserParser p, int id) {
    super(p, id);
    }

    public void execute() {
        System.out.println("FILENAME");
    }

    public Object jjtGetValue() { return name; }

    public String toString() { return AutoAnalyserParserTreeConstants.jjtNodeName[id] + " " + name; }
}
/* JavaCC - OriginalChecksum=21f49ebf363963b382e2ad8a58e0066e (do not edit this line) */
