/* Generated By:JJTree: Do not edit this line. Identifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class Identifier extends SimpleNode {

  String name = null;

  public Identifier(int id) {
    super(id);
  }

  public Identifier(AutoAnalyserParser p, int id) {
    super(p, id);
  }


    public Automata execute() {
        System.out.println("IDENTIFIER");
        return null;
    }

    public Object jjtGetValue() { return name; }

    public String toString() { return AutoAnalyserParserTreeConstants.jjtNodeName[id] + " " + name; }
}
/* JavaCC - OriginalChecksum=0dd9f8e06beb9b75cb117c6fd838a0d5 (do not edit this line) */
