/* Generated By:JJTree: Do not edit this line. Input.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class Input extends SimpleNode {

  String name = null;

  public Input(int id) {
    super(id);
  }

  public Input(AutoAnalyserParser p, int id) {
    super(p, id);
  }

  public Automata execute() {
      System.out.println("INPUT");
      return null;
  }

  public Object jjtGetValue() { return name; }

  public String toString() { return AutoAnalyserParserTreeConstants.jjtNodeName[id] + " " + name; }
}
/* JavaCC - OriginalChecksum=f0b7232bdcc5ab84f35009afb9ef4124 (do not edit this line) */
