/* Generated By:JJTree: Do not edit this line. input.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class input extends SimpleNode {

  public String name = null;

  public input(int id) {
    super(id);
  }

  public input(AutoAnalyserParser p, int id) {
    super(p, id);
  }

  public void execute() {
      System.out.println("INPUT");
  }

  public Object jjtGetValue() { return name; }

  public String toString() { return AutoAnalyserParserTreeConstants.jjtNodeName[id] + " " + name; }

}
/* JavaCC - OriginalChecksum=fc132c5c9390f690e0c4f5f33cc149e4 (do not edit this line) */
