/* Generated By:JJTree: Do not edit this line. Intersection.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class Intersection extends SimpleNode {
  public Intersection(int id) {
    super(id);
  }

  public Intersection(AutoAnalyserParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=47f8257f2ff939d70d470d42c65ff8fb (do not edit this line) */
