/* Generated By:JJTree: Do not edit this line. Intersection.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class Intersection extends SimpleNode {
  public Intersection(int id) {
    super(id);
  }

  public Intersection(AutoAnalyserParser p, int id) {
    super(p, id);
  }

  public Automata execute(){
    Automata aut1 = null;
    Automata aut2 = null;
    Automata out = null;

    for(int i=0; i < children.length; i++) {
      if (children[i] instanceof Expr2){
        aut1 = children[i].execute();
      } else if (children[i] instanceof Expr1){
        aut2 = children[i].execute();
      } else {
        System.out.println("Shouldn't go here! (Intersecion)");
      }
    }

    //TODO Automata out = getIntersection(aut1, aut2);

    return out;
  }

}
/* JavaCC - OriginalChecksum=47f8257f2ff939d70d470d42c65ff8fb (do not edit this line) */
