/* Generated By:JJTree: Do not edit this line. loaddotty.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class loaddotty extends SimpleNode {
  public loaddotty(int id) {
    super(id);
  }

  public loaddotty(AutoAnalyserParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=603e08197b70bff494d52b5a08401225 (do not edit this line) */
