/* Generated By:JJTree: Do not edit this line. operations.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class operations extends SimpleNode {
  public operations(int id) {
    super(id);
  }

  public operations(AutoAnalyserParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fa5980d18b3ca0765fab7a4e900d5fec (do not edit this line) */
