/* Generated By:JJTree: Do not edit this line. read.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class read extends SimpleNode {
  public read(int id) {
    super(id);
  }

  public read(AutoAnalyserParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bc85757b69b45a932f95113095bf9e18 (do not edit this line) */
