/* Generated By:JJTree: Do not edit this line. Read.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class Read extends SimpleNode {
  public Read(int id) {
    super(id);
  }

  public Read(AutoAnalyserParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e1786b2d37b4a14ec4a06ef2a31d77ea (do not edit this line) */
