/* Generated By:JJTree: Do not edit this line. Reverse.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class Reverse extends SimpleNode {
  public Reverse(int id) {
    super(id);
  }

  public Reverse(AutoAnalyserParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5482a5d2823f1fb85f495cb8a0613baa (do not edit this line) */
