/* Generated By:JJTree: Do not edit this line. saves.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class saves extends SimpleNode {
  public saves(int id) {
    super(id);
  }

  public saves(AutoAnalyserParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5bd6f4fa3268941d577e515a075d297b (do not edit this line) */
