/* Generated By:JJTree: Do not edit this line. Saves.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class Saves extends SimpleNode {
  public Saves(int id) {
    super(id);
  }

  public Saves(AutoAnalyserParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1c4388ad58f2690ef9fba3d2351b314d (do not edit this line) */
