/* Generated By:JJTree: Do not edit this line. start.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class start extends SimpleNode {
  public start(int id) {
    super(id);
  }

  public start(AutoAnalyserParser p, int id) {
    super(p, id);
  }
  
  public void execute() {
	System.out.println("Start");
  	for(int i = 0; i < children.length ; i++) {
      	children[i].execute();
      	System.out.println("Execute " + children[i].toString());
  	}
  
  }
 
}
/* JavaCC - OriginalChecksum=598994b6409c3d3955b1bdd4b4c2af2c (do not edit this line) */
