/* Generated By:JJTree: Do not edit this line. start.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class start extends SimpleNode {
  public start(int id) {
    super(id);
  }

  public start(AutoAnalyserParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=598994b6409c3d3955b1bdd4b4c2af2c (do not edit this line) */
