/* Generated By:JJTree: Do not edit this line. Sum.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class Sum extends SimpleNode {
  public Sum(int id) {
    super(id);
  }

  public Sum(AutoAnalyserParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=affce69b92736c2c13ae0d52451ab1b5 (do not edit this line) */
