/* Generated By:JJTree: Do not edit this line. sum.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class sum extends SimpleNode {
  public sum(int id) {
    super(id);
  }

  public sum(AutoAnalyserParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9c38a72212178b9cca8038ad4824bfd8 (do not edit this line) */
