/* Generated By:JJTree: Do not edit this line. Union.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class Union extends SimpleNode {
  public Union(int id) {
    super(id);
  }

  public Union(AutoAnalyserParser p, int id) {
    super(p, id);
  }

  public Automata execute(){
    for(int i=0; i < children.length; i++) {
      if (children[i] instanceof Identifier){
        System.out.println(((Identifier) children[i]).name);
      } else if (children[i] instanceof Expr1){
        children[i].execute();
      } else {
        System.out.println(children[i]);
      }
    }
    return null;
  }

}
/* JavaCC - OriginalChecksum=9b7c56766f2c48096224f1bf573dae0e (do not edit this line) */
