/* Generated By:JJTree: Do not edit this line. union.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class union extends SimpleNode {
  public union(int id) {
    super(id);
  }

  public union(AutoAnalyserParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=92c2d3c4559758820672cb1a4ab1cb5d (do not edit this line) */
